### ISSUE TITLE
Preferences tab bug (keeps rendering indefinitely)

### ISSUE THREAD

**Issue by amadeusjustinn** [vord1080/clipboard2file#13]
When I click the Preferences tab from the add-ons menu in Firefox 108.0, this happens:

https://user-images.githubusercontent.com/67861264/208380692-e938096b-736a-4d3f-86d3-48f4412badfc.mov

The view keeps generating whitespace below the actual preferences indefinitely.

**Comment by vord1080** [comment]
That is....very strange! Unfortunately I cannot get that to happen on any of my computers. Does uninstalling and reinstalling the extension help?

**Comment by amadeusjustinn** [comment]
https://user-images.githubusercontent.com/67861264/208961667-7796c824-58b2-4317-b101-1134ea8dae82.mov
Unfortunately, the bug persists after removing and reinstalling the extension.

**Comment by vord1080** [comment]
I truly have no idea what could be causing this. I don't see anything in the code that could result in this happening. 

Perhaps, you're hitting an obscure layout bug caused by the combination of your screen size/dpi/window size/the css of the settings page/?

Does this only happen in about:addons or can you get it to happen when navigating directly to the page? Try visiting moz-extension://YOUR_EXTENSION_ID_HERE/settings/settings.html

(To get the extension id, go to about:debugging, find clipboard2file, copy the "Internal UUID" and replace YOUR_EXTENSION_ID_HERE with it)

**Comment by amadeusjustinn** [comment]
<img width="1680" alt="Screenshot 2022-12-21 at 11 58 09 AM" src="https://user-images.githubusercontent.com/67861264/208972632-593edad0-a69b-4851-b813-47a3d0b803f3.png">

Actually, the infinite rendering does not happen with the method you described. Very strange!

**Comment by vord1080** [comment]
I've been doing some debugging....still completely lost. I would suggest bringing this to Mozilla's attention at bugzilla.mozilla.org

**Comment by Veirt** [comment]
I can reproduce this. Made a pull request here: #18

https://github.com/vord1080/clipboard2file/assets/55097092/dbaafcf1-d535-4c52-90be-04ae0453eed5

**Comment by amadeusjustinn** [comment]
@Veirt Thank you so much for your help!

**Comment by Veirt** [comment]
You're welcome! :)
